# Site settings
title: Jorik Tangelder
email: j.tangelder@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal blog of Jorik Tangelder.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://joriktangelder.nl" # the base hostname & protocol for your site
twitter_username: jorikdelaporik
github_username:  jtangelder

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
